version: '3.1'

services:

  db:
    image: postgres:9.5.1
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: admin
      POSTGRES_DB: some_db_dev
    ports:
      - 5432:5432
    volumes:
      - /home/caio/Workspace/investing/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
